"""Add template model and user relationship

Revision ID: 86c2d5d5addb
Revises: e33f84ff6696
Create Date: 2024-12-16 02:56:08.630242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86c2d5d5addb'
down_revision: Union[str, None] = 'e33f84ff6696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
